In [1]:
import pandas as pd 
import torch 


In [3]:
d,k=10,10
w_rank=2
w=torch.randn(d,w_rank) @ torch.randn(w_rank,k)
print(w)


tensor([[-1.1191e-01,  6.2453e-01,  2.5221e-01,  5.9521e-01,  2.9812e-01,
         -1.4352e-01,  2.0278e-01, -1.2874e+00, -9.6245e-01,  5.4036e-01],
        [-4.8489e+00,  5.0834e-01,  5.3080e-01, -1.1903e+00, -4.7986e-01,
          2.1572e+00, -2.2989e-01,  3.2331e+00,  3.2669e+00, -1.4971e+00],
        [ 3.0097e+00, -1.4606e+00, -7.7785e-01, -4.2473e-01, -2.7993e-01,
         -9.7774e-01, -2.4614e-01,  5.3834e-01, -8.8401e-02, -1.4504e-01],
        [ 3.9117e+00, -2.7074e+00, -1.3278e+00, -1.3741e+00, -7.7203e-01,
         -1.0156e+00, -5.9463e-01,  2.4978e+00,  1.2553e+00, -9.4752e-01],
        [-1.3382e+00,  6.6216e-01,  3.5084e-01,  2.0179e-01,  1.3089e-01,
          4.3071e-01,  1.1377e-01, -2.6767e-01,  1.7730e-02,  7.6441e-02],
        [-3.2770e+00,  1.9939e+00,  1.0050e+00,  8.7245e-01,  5.0838e-01,
          9.3733e-01,  4.0502e-01, -1.4830e+00, -5.8709e-01,  5.3647e-01],
        [-2.5467e+00,  1.8214e+00,  8.8746e-01,  9.5429e-01,  5.3227e-01,
          6.4266e-01,  4.0708e-0

In [4]:
u,s,v=torch.svd(w)
u_r=u[:,:w_rank]
s_r=torch.diag(s[:w_rank])
v_r=v[:,:w_rank].T

b=u_r @ s_r
a=v_r

In [6]:
bias=torch.randn(d)
x=torch.randn(d)
y=w@x+bias
y_2=(b@a)@x + bias

print(y)
print(y_2)

print(w.nelement())
print(b.nelement()+a.nelement())



tensor([ -5.3267,   3.5230,   7.3089,  14.9082,  -3.7752, -10.0483, -11.5644,
         -1.5521,   7.5218,  -7.3797])
tensor([ -5.3267,   3.5230,   7.3089,  14.9082,  -3.7752, -10.0483, -11.5644,
         -1.5521,   7.5218,  -7.3797])
100
40
